# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "estate_type",
                    models.CharField(
                        choices=[
                            ("gated", "Gated Community"),
                            ("mixed_use", "Mixed Use"),
                            ("apartment", "Apartment Complex"),
                            ("townhouse", "Townhouse Estate"),
                            ("commercial", "Commercial Estate"),
                        ],
                        default="gated",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="estates/logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="estates/covers/"
                    ),
                ),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="NG", max_length=2)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("timezone", models.CharField(default="Africa/Lagos", max_length=50)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("locale", models.CharField(default="en-NG", max_length=10)),
                ("total_units", models.PositiveIntegerField(default=0)),
                ("occupied_units", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("onboarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "estates_estate",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="estates_est_slug_56ce32_idx"
                    ),
                    models.Index(
                        fields=["city", "country"], name="estates_est_city_c91dc6_idx"
                    ),
                    models.Index(
                        fields=["is_active", "is_deleted"],
                        name="estates_est_is_acti_8e80ca_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("floor_count", models.PositiveSmallIntegerField(default=1)),
                ("unit_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="estates.estate",
                    ),
                ),
            ],
            options={
                "db_table": "estates_block",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("unit_number", models.CharField(db_index=True, max_length=50)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("townhouse", "Townhouse"),
                            ("penthouse", "Penthouse"),
                            ("commercial", "Commercial"),
                            ("studio", "Studio"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                ("floor", models.SmallIntegerField(default=0)),
                ("bedrooms", models.PositiveSmallIntegerField(default=1)),
                ("bathrooms", models.PositiveSmallIntegerField(default=1)),
                (
                    "square_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        db_index=True,
                        default="vacant",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_service_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="estates.block",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="estates.estate",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "estates_unit",
            },
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["estate", "is_active"], name="estates_blo_estate__125ac5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("estate", "code")},
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["estate", "occupancy_status"],
                name="estates_uni_estate__2e85ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["estate", "block", "unit_number"],
                name="estates_uni_estate__9ae03b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["owner"], name="estates_uni_owner_i_e280b9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("estate", "unit_number")},
        ),
    ]
