# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilityAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("gas", "Gas"),
                            ("internet", "Internet"),
                            ("waste", "Waste Management"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(db_index=True, max_length=100)),
                ("meter_number", models.CharField(blank=True, max_length=100)),
                ("provider_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("disconnected", "Disconnected"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "last_reading",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("last_reading_date", models.DateField(blank=True, null=True)),
                ("tariff_plan", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_accounts",
                        to="estates.unit",
                    ),
                ),
            ],
            options={
                "db_table": "utilities_account",
            },
        ),
        migrations.CreateModel(
            name="ConsumptionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reading_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "previous_reading",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "current_reading",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("consumption", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("is_estimated", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_records",
                        to="utilities.utilityaccount",
                    ),
                ),
            ],
            options={
                "db_table": "utilities_consumption_record",
            },
        ),
        migrations.CreateModel(
            name="UtilityTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Token Purchase"),
                            ("payment", "Bill Payment"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "units_purchased",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="utilities.utilityaccount",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "utilities_transaction",
            },
        ),
        migrations.AddIndex(
            model_name="utilityaccount",
            index=models.Index(
                fields=["estate", "utility_type", "status"],
                name="utilities_a_estate__699325_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="utilityaccount",
            index=models.Index(
                fields=["unit", "utility_type"], name="utilities_a_unit_id_ecc378_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="utilityaccount",
            unique_together={("estate", "utility_type", "account_number")},
        ),
        migrations.AddIndex(
            model_name="consumptionrecord",
            index=models.Index(
                fields=["estate", "account", "reading_date"],
                name="utilities_c_estate__a0da8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumptionrecord",
            index=models.Index(
                fields=["reading_date"], name="utilities_c_reading_2ffc9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="utilitytransaction",
            index=models.Index(
                fields=["estate", "status", "created_at"],
                name="utilities_t_estate__8c7da2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="utilitytransaction",
            index=models.Index(
                fields=["account", "transaction_type"],
                name="utilities_t_account_4e1a48_idx",
            ),
        ),
    ]
