# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        ("residents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("visitor_name", models.CharField(max_length=255)),
                ("visitor_phone", models.CharField(blank=True, max_length=20)),
                ("visitor_email", models.EmailField(blank=True, max_length=254)),
                ("visitor_company", models.CharField(blank=True, max_length=255)),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Entry"),
                            ("multi", "Multi Entry"),
                            ("recurring", "Recurring"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("access_code", models.CharField(blank=True, max_length=10)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("max_entries", models.PositiveSmallIntegerField(default=1)),
                ("entries_used", models.PositiveSmallIntegerField(default=0)),
                ("vehicle_plate", models.CharField(blank=True, max_length=20)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/photos/%Y/%m/"
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_passes",
                        to="residents.residentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "visitors_pass",
            },
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("visitor_name", models.CharField(max_length=255)),
                ("visitor_phone", models.CharField(blank=True, max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("entry", "Entry"), ("exit", "Exit")], max_length=10
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("qr", "QR Code"),
                            ("manual", "Manual"),
                            ("rfid", "RFID"),
                            ("otp", "OTP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gate_name", models.CharField(blank=True, max_length=100)),
                ("vehicle_plate", models.CharField(blank=True, max_length=20)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/logs/%Y/%m/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs",
                        to="residents.residentprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_visitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="visitors.visitorpass",
                    ),
                ),
            ],
            options={
                "db_table": "visitors_log",
            },
        ),
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "id_document_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "license_plate",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/blacklist/%Y/%m/"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("security", "Security Incident"),
                            ("trespass", "Trespassing"),
                            ("fraud", "Fraud"),
                            ("disturbance", "Disturbance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklist_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "visitors_blacklist",
                "indexes": [
                    models.Index(
                        fields=["estate", "is_active"],
                        name="visitors_bl_estate__b93445_idx",
                    ),
                    models.Index(
                        fields=["full_name", "phone"],
                        name="visitors_bl_full_na_ff478c_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["estate", "status", "valid_until"],
                name="visitors_pa_estate__230c51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["host", "status"], name="visitors_pa_host_id_2e1960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorpass",
            index=models.Index(
                fields=["qr_code"], name="visitors_pa_qr_code_1a31d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["estate", "timestamp"], name="visitors_lo_estate__b9f7df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["estate", "direction", "timestamp"],
                name="visitors_lo_estate__a5c176_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["visitor_pass"], name="visitors_lo_visitor_d47d25_idx"
            ),
        ),
    ]
