# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart"),
                            ("kpi", "KPI Card"),
                            ("table", "Table"),
                            ("map", "Map"),
                            ("list", "List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("query_config", models.JSONField(default=dict)),
                ("display_config", models.JSONField(default=dict)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=300)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_dashboard_widget",
                "indexes": [
                    models.Index(
                        fields=["estate", "is_active", "sort_order"],
                        name="analytics_d_estate__c0fac6_idx",
                    )
                ],
                "unique_together": {("estate", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("metric_key", models.CharField(db_index=True, max_length=100)),
                ("metric_name", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_metric_snapshot",
                "indexes": [
                    models.Index(
                        fields=["estate", "metric_key", "recorded_at"],
                        name="analytics_m_estate__c61b4a_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="analytics_m_recorde_086e58_idx"
                    ),
                ],
            },
        ),
    ]
