# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("slot_number", models.CharField(db_index=True, max_length=50)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("resident", "Resident"),
                            ("visitor", "Visitor"),
                            ("ev", "EV Charging"),
                            ("disabled", "Disabled Access"),
                            ("commercial", "Commercial"),
                        ],
                        default="resident",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("has_ev_charger", models.BooleanField(default=False)),
                ("is_covered", models.BooleanField(default=False)),
                (
                    "monthly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estates.block",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parking_slots",
                        to="estates.unit",
                    ),
                ),
            ],
            options={
                "db_table": "parking_slot",
            },
        ),
        migrations.CreateModel(
            name="ParkingPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("permit_number", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField(db_index=True)),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_permits",
                        to="residents.residentprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_permits",
                        to="residents.vehicle",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permits",
                        to="parking.parkingslot",
                    ),
                ),
            ],
            options={
                "db_table": "parking_permit",
            },
        ),
        migrations.CreateModel(
            name="EVChargingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "energy_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("charger_id", models.CharField(blank=True, max_length=100)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ev_sessions",
                        to="residents.residentprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ev_sessions",
                        to="residents.vehicle",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ev_sessions",
                        to="parking.parkingslot",
                    ),
                ),
            ],
            options={
                "db_table": "parking_ev_charging_session",
            },
        ),
        migrations.AddIndex(
            model_name="parkingslot",
            index=models.Index(
                fields=["estate", "slot_type", "status"],
                name="parking_slo_estate__4868d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkingslot",
            index=models.Index(fields=["unit"], name="parking_slo_unit_id_912126_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="parkingslot",
            unique_together={("estate", "slot_number")},
        ),
        migrations.AddIndex(
            model_name="parkingpermit",
            index=models.Index(
                fields=["estate", "status", "valid_until"],
                name="parking_per_estate__1ba43a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkingpermit",
            index=models.Index(
                fields=["vehicle", "status"], name="parking_per_vehicle_0907df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parkingpermit",
            unique_together={("estate", "permit_number")},
        ),
        migrations.AddIndex(
            model_name="evchargingsession",
            index=models.Index(
                fields=["estate", "status", "started_at"],
                name="parking_ev__estate__225818_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evchargingsession",
            index=models.Index(
                fields=["vehicle", "status"], name="parking_ev__vehicle_5cf7e6_idx"
            ),
        ),
    ]
