# Generated by Django 6.0.6 on 2026-06-11 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("estate.created", "Estate created"),
                            ("estate.updated", "Estate updated"),
                            ("estate.deactivated", "Estate deactivated"),
                            ("estate.activated", "Estate activated"),
                            ("admin.assigned", "Admin assigned"),
                            ("admin.revoked", "Admin revoked"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=64)),
                ("resource_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("summary", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_logs",
                        to="estates.estate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "action"],
                        name="platform_ad_created_cc4add_idx",
                    )
                ],
            },
        ),
    ]
