# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                            ("stripe", "Stripe"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("public_key", models.CharField(blank=True, max_length=255)),
                ("secret_key_encrypted", models.TextField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("supported_currencies", models.JSONField(default=list)),
                ("supported_methods", models.JSONField(default=list)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
            ],
            options={
                "db_table": "payments_provider_config",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("callback_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("related_object_type", models.CharField(blank=True, max_length=100)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "provider_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="payments.paymentproviderconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_transaction",
            },
        ),
        migrations.AddIndex(
            model_name="paymentproviderconfig",
            index=models.Index(
                fields=["estate", "is_active", "is_default"],
                name="payments_pr_estate__14ee1f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentproviderconfig",
            unique_together={("estate", "provider")},
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["estate", "status", "created_at"],
                name="payments_tr_estate__d195ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "status"], name="payments_tr_user_id_b99a80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["reference"], name="payments_tr_referen_530efe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="payments_tr_related_2038f2_idx",
            ),
        ),
    ]
