# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resident_type",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("tenant", "Tenant"),
                            ("family", "Family Member"),
                            ("staff", "Staff"),
                        ],
                        default="owner",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Approval"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("move_out_date", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("id_document_type", models.CharField(blank=True, max_length=50)),
                ("id_document_number", models.CharField(blank=True, max_length=100)),
                (
                    "id_document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="residents/documents/%Y/%m/"
                    ),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="estates.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "residents_profile",
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="residents/family/%Y/%m/"
                    ),
                ),
                ("has_gate_access", models.BooleanField(default=False)),
                ("access_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="residents.residentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "residents_family_member",
            },
        ),
        migrations.CreateModel(
            name="DomesticStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("nanny", "Nanny"),
                            ("driver", "Driver"),
                            ("cook", "Cook"),
                            ("cleaner", "Cleaner"),
                            ("gardener", "Gardener"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="residents/staff/%Y/%m/"
                    ),
                ),
                ("id_document_number", models.CharField(blank=True, max_length=100)),
                ("has_gate_access", models.BooleanField(default=True)),
                ("access_schedule", models.JSONField(blank=True, default=dict)),
                ("employment_start", models.DateField(blank=True, null=True)),
                ("employment_end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_staff",
                        to="residents.residentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "residents_domestic_staff",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("suv", "SUV"),
                            ("motorcycle", "Motorcycle"),
                            ("truck", "Truck"),
                            ("ev", "Electric Vehicle"),
                        ],
                        default="car",
                        max_length=20,
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("license_plate", models.CharField(db_index=True, max_length=20)),
                ("registration_number", models.CharField(blank=True, max_length=50)),
                ("registration_expiry", models.DateField(blank=True, null=True)),
                (
                    "rfid_tag",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("is_ev", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="residents/vehicles/%Y/%m/"
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="residents.residentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "residents_vehicle",
            },
        ),
        migrations.AddIndex(
            model_name="residentprofile",
            index=models.Index(
                fields=["estate", "user", "status"],
                name="residents_p_estate__18841f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="residentprofile",
            index=models.Index(
                fields=["estate", "unit", "is_primary"],
                name="residents_p_estate__79b279_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="residentprofile",
            index=models.Index(
                fields=["resident_type", "status"],
                name="residents_p_residen_31aafb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["estate", "primary_resident", "is_active"],
                name="residents_f_estate__47af51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="domesticstaff",
            index=models.Index(
                fields=["estate", "employer", "is_active"],
                name="residents_d_estate__cc6f60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["estate", "owner", "is_active"],
                name="residents_v_estate__3d08f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["license_plate"], name="residents_v_license_4e19c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("estate", "license_plate")},
        ),
    ]
