# Generated by Django 6.0.6 on 2026-06-11 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0001_initial"),
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residentprofile",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="estates.unit",
            ),
        ),
    ]
