# Generated by Django 6.0.6 on 2026-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0002_nullable_unit_for_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residentprofile",
            name="resident_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Owner"),
                    ("tenant", "Tenant"),
                    ("family", "Family Member"),
                    ("staff", "Staff"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
    ]
