# Generated by Django 6.0.6 on 2026-06-10 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        ("residents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("doctor_name", models.CharField(blank=True, max_length=255)),
                ("hospital_name", models.CharField(blank=True, max_length=255)),
                (
                    "prescription_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("fulfilled", "Fulfilled"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="pharmacy/prescriptions/%Y/%m/")),
                ("medications", models.JSONField(default=list)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="residents.residentprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_prescription",
            },
        ),
        migrations.CreateModel(
            name="MedicationOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("order_number", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready for Pickup"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("items", models.JSONField(default=list)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("delivery_type", models.CharField(default="pickup", max_length=20)),
                ("delivery_address", models.TextField(blank=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_orders",
                        to="residents.residentprofile",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_medication_order",
            },
        ),
        migrations.CreateModel(
            name="DrugReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("medication_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("schedule", models.JSONField(default=list)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="estates.estate",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_reminders",
                        to="residents.residentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_drug_reminder",
                "indexes": [
                    models.Index(
                        fields=["estate", "resident", "is_active"],
                        name="pharmacy_dr_estate__b55203_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["estate", "resident", "status"],
                name="pharmacy_pr_estate__8e15c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["expiry_date", "status"], name="pharmacy_pr_expiry__5bcd86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationorder",
            index=models.Index(
                fields=["estate", "status", "created_at"],
                name="pharmacy_me_estate__2394f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationorder",
            index=models.Index(
                fields=["resident", "status"], name="pharmacy_me_residen_7edd25_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicationorder",
            unique_together={("estate", "order_number")},
        ),
    ]
